Refactor To-Do List Server for Better Task Management
KhanyiCodes/To-Do-List pull request #1
Opened 2024-11-07 13:38 UTC by KhanyiCodes

This pull request refactors the To-Do List server code to improve the structure, performance, and maintainability of the task management functionality. The changes are aimed at enhancing the way tasks are handled in the backend, including making the code more modular, improving error handling, validating inputs, and optimizing data storage

Key Changes:
Improved Code Structure and Modularity:
The server code has been refactored to follow better modular practices.
Before: The server file contained all the logic, which made it bulky and difficult to scale.
After: The logic has been organized into separate modules for clarity and maintainability.

Enhanced Task Management API:
Task Validation: We now ensure that all tasks being added to the list contain valid input. Tasks must have a non-empty text field before being added.
Completion Handling: Added validation to mark tasks as completed only when they exist. If the task doesn't exist, a 404 Not Found error is returned.
Error Handling: Proper error responses have been added. For instance, if a user tries to add a task with invalid input, they now receive a clear error message (400 Bad Request).

2024-11-08 02:27 UTC, PhodzoW0l7 reviewed
Well structured project.

2024-11-08 02:27 UTC, PhodzoW0l7 commented on public/index.html
Well structured format.

2024-11-08 02:27 UTC, PhodzoW0l7 commented on public/script.js
Well structured format but I would suggest adding a message for creation and deletion of a task,

2024-11-08 07:23 UTC, bokangkhumalo requested changes
Hi @KhanyiCodes,

🚀 Code Review Summary
Fantastic job on building the core functionality! Here are a few suggestions that could enhance readability and maintainability:

✍️ 1. Add Comments to Key Sections
The code currently lacks comments, which makes it challenging to follow, especially in complex areas like data processing and logic flow. Adding brief comments to summarize each section would make the code easier to read and understand.

🔍 2. Improve Naming for Clarity
Some function and variable names could be more descriptive to reflect their purpose. Clearer naming can often replace the need for comments, making the code more self-explanatory.

📄 3. Add Documentation or a README
Including a brief README or module-level docstrings to explain the overall structure and purpose of each module would be helpful for future contributors. This would give new readers a clear starting point.

Looking forward to seeing these changes

2024-11-08 12:23 UTC, Tepanyega requested changes
Kindly ensure that the requested changes are made before the end of the day.

2024-11-08 12:23 UTC, Tepanyega commented on public/style.css
> +}
hi @KhanyiCodes,
Can you ensure that when you mark your task as completed, the delete button is not displayed with a line-through?

2024-11-12 12:23 UTC, JKRakuba approved these changes

2024-11-12 13:09 UTC, KhanyiCodes reviewed
Updated

2024-11-12 13:09 UTC, KhanyiCodes commented on public/style.css
> +}
Hello @Tepanyega , yes I fixed it and placed it as a separate list without a line through the deleted button

2024-11-12 13:09 UTC, KhanyiCodes commented on public/script.js
Thank you, I created pop up messages. 
Delete:
![image](https://github.com/user-attachments/assets/3a8943db-1291-43d4-8e7c-a8ceadd3898c)
Create:
![image](https://github.com/user-attachments/assets/9163272e-df92-4305-ae42-76f9303cd22b)

2024-11-12 13:52 UTC, PhodzoW0l7 approved these changes
Everything looks okay and working.

2024-11-12 13:57 UTC, Tepanyega approved these changes
happy coding

2024-11-13 07:24 UTC, alphineandre approved these changes
Great Work!! Looks amazing...

2024-11-13 07:24 UTC, alphineandre commented on public/app.js
Functionalities look good.

2024-11-13 07:24 UTC, alphineandre commented on public/index.html
Structure looks good. But separate the task categories to account for access space around the list.

2024-11-13 07:24 UTC, alphineandre commented on public/style.css
Design looks good. Nice touch with the neon.

2024-11-13 07:27 UTC, Tepanyega approved these changes

2024-11-15 06:44 UTC, bokangkhumalo approved these changes
Hi  @KhanyiCodes, Thanks for creating a Fully functional To-do list.

2024-11-15 07:45 UTC, merged